AksApp/Controllers/AccessController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using AksApp.Models;
using AksApp.Data;

namespace AksApp.Controllers
{
    

    public class AccessController : Controller
    {
        public ApplicationDbContext _db;

        public AccessController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Login()
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            if (claimUser.Identity.IsAuthenticated)
                return RedirectToAction("admin", "Admin");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserCredentials modelLogin)

        {
            if (modelLogin.Email == _db.userCredentials.Find(2).Email && modelLogin.Password == _db.userCredentials.Find(2).Password
                )
            {
                List<Claim> claims = new List<Claim>()
                {
                    new Claim(ClaimTypes.NameIdentifier, modelLogin.Email),
                    new Claim("OtherProperties", "Example Role")
                };

                ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                AuthenticationProperties properties = new AuthenticationProperties()
                {
                    AllowRefresh = true,
                    IsPersistent = modelLogin.KeepLoggedIn

                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity), properties);
                return RedirectToAction("admin", "Admin");
            }
            string errMsg = " User Not Found";
            ViewData["ErrorMessage"] = errMsg;
            return View();
        }
    }
}

AksApp/Views/Access/Login.cshtml
@model UserCredentials

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>AKS Machine Test</title>
    <link rel="stylesheet" href="css/style.css">
    <!--[if lt IE 9]>
    <script type="text/javascript" src="html5.js"></script>
    <![endif]-->
    <!--[if lt IE 7.]>
    <script defer type="text/javascript" src="pngfix1.js"></script>
    <![endif]-->
    <!-- Menu start --------------->
    <link href="menu/quickmenu0.css" rel="stylesheet" type="text/css" media="screen" />
    <script type="text/javascript" src="menu/quickmenu0.js"></script>
    <!-- Menu End --------------->
</head>
<body>
    <header>
        <div id="wrap">
            <div class="logo"><img src="images/logo.png" border="0"></div>

            <div class="admintxt">Admin panel</div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </header>
    <div class="clear"></div>
    <div class="bodycont">
        <div id="wrap2" style="min-height:530px;">
            <div class="login-cont">
                <h1 class="loginhd">Login Here</h1>
                <form asp-controller="Access" asp-action="Login" method="post">
                    <h3 style="color: red">@TempData["ErrorMessage"]</h3>
                    <div class="login-row">
                    <div class="loginname">Email</div>
                    <div class="admintxtfld-box">
                            <input asp-for="Email" type="email" name="email">
                        <span asp-validation-for="Email"></span>
                    </div>
                    <div class="clear"></div>
                </div>
                <!--       <div class="loginreq-field">* This Field Required </div> -->
                    
                <div class="login-row">
                    <div class="loginname">Password</div>
                    <div class="admintxtfld-box">
                        <input asp-for="Password" type="password" name="password">
                        
                    </div>

                    <div class="clear"></div>
                </div>

                <div class="clear"></div>
                <div class="contact-row" style="width:325px;">
                    <div style="background:none; border:none; margin-top:15px;">
                        <a href="admin.html" style="text-decoration:none;">
                            <input type="submit" class="btn" value="Login">
                        </a><br>
                    </div>
                </div>
                </form>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <footer>
        <footer class="whitefoter">
            <div class="whitefooter-cont">
                <div style="float:left;">Copyright © AKS Machine Test. All Rights Reserved.</div>
                <a href="https://www.akswebsoft.com/" target="_blank" style="float:right;">
                    <img src="images/akslogo.png" alt="AKS Websoft Consulting Pvt. Ltd." title="AKS Websoft Consulting Pvt. Ltd.">
                </a>

                <div class="clear"></div>
            </div>
        </footer>
    </footer>
</body>
</html>