AksApp/Models/SubCategory.cs
using System.ComponentModel.DataAnnotations;

namespace AksApp.Models
{
    public class SubCategory
    {
        public int SubCategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public string Category_Name { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }

        public bool IsActive { get; set; }
    }
}

AksApp/Controllers/AdminController.cs
using AksApp.Data;
using AksApp.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AksApp.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        /*       public readonly ApplicationDbContext _db;

               public AdminController(ApplicationDbContext db)
               {
                   _db = db;
               }


               [HttpPost]
               public ActionResult CheakCredential(UserCredentials crd)
               {
                   // Process the form data here
                   if(ModelState.IsValid)
                   {
                       var objCredententialList = _db.userCredentials.Find(2);
                       if(objCredententialList.Email== crd.Email && objCredententialList.Email!=null)
                       {
                           if(objCredententialList.Password== crd.Password && objCredententialList.Password!=null) {
                             return RedirectToAction("admin");
                           }
                       }
                       else
                       {
                           string errorMsg = "Your credentials are invalid. Please try again.";
                           TempData["ErrorMessage"] = errorMsg;
                           return Redirect("../");
                       }
                   }
                   string errorMsg1 = "Your credentials are invalid. Please try again.";
                   TempData["ErrorMessage"] = errorMsg1;
                   return Redirect("../");
               }
        */
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Access");
        }
        public IActionResult admin()
        {
            return View();
        }
    }
}

AksApp/Controllers/CategoryController.cs
using AksApp.Data;
using AksApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AksApp.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        public readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }


        public IActionResult Create()
        {

            IEnumerable<Category> objCategoriesList = _db.Categories.ToList();

            ViewData["ModelList"] = objCategoriesList;
            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj)
        {
            if (obj.CategoryName!=null && obj.IsActive!=null)
            {
                _db.Categories.Add(obj);
                _db.SaveChanges();
                IEnumerable<Category> objCategoriesList = _db.Categories.ToList();
                ViewData["ModelList"] = objCategoriesList;
                return View();
            }
            return View(obj);
        }


        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();
            var categoryFromDb = _db.Categories.Find(id);
            if (categoryFromDb == null)
                return NotFound();

            return View(categoryFromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.CategoryName!=null)
            {
                _db.Categories.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Create");
            }
            return RedirectToAction("Create");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();
            var obj = _db.Categories.Find(id);
            if (obj == null)
                return NotFound();
            else
            {
                _db.Categories.Remove(obj);
                _db.SaveChanges();
            }
            return RedirectToAction("Create");
        }
 /*       [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Categories.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Categories.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
 */


    }
}

AksApp/Controllers/ChangePasswordController.cs
using AksApp.Data;
using AksApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AksApp.Controllers
{
    [Authorize]
    public class ChangePasswordController : Controller
    {
        public ApplicationDbContext _db;

        public ChangePasswordController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(ChangePassword obj)
        {
            
            if (ModelState.IsValid)
            {
                if (obj.oldPassWord == _db.userCredentials.Find(2).Password)
                {
                    if(obj.newPassWord == obj.confirmPassWord)
                    {
                        var entity = _db.userCredentials.SingleOrDefault(x => x.Id == 2);
                        entity.Password = obj.newPassWord;
                        _db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        string errorMsg = "Both New Password And OldPassWord Should Be Same";
                        TempData["ErrorMessage"] = errorMsg;
                        return View(obj);
                    }

                }
                else
                {
                    string errorMsg1 = "Invalid Current Password";
                    TempData["ErrorMessage"] = errorMsg1;
                    return View(obj);
                }
            }
            string errorMsg2 = "Pleas Enter Valid Input";
            TempData["ErrorMessage"] = errorMsg2;
            return View(obj);
        }
    }
}

AksApp/Controllers/ProductController.cs
using AksApp.Data;
using AksApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AksApp.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        string  directoryPath = @"C:\Users\Sahil\source\repos\Aks\AksApp\UserDataFile\";
        private readonly ApplicationDbContext _dbContext;
        public ProductController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index()
        {
            ViewBag.CategoryList = new SelectList(_dbContext.Categories, "CategoryId", "CategoryName");
            IEnumerable<Product> objCategoriesList = _dbContext.Product.ToList();
            ViewData["ProductData"] = objCategoriesList;
            return View();
        }

        public IActionResult Create(DummyProduct dp)
        {
            if(!setDummyProductToPrduct(dp))
            {
                string errMsg = "All Field Required";
                ViewData["fieldnotfilled"] =  errMsg;
            }
            return RedirectToAction("Index");
        }


        public JsonResult GetSubCategoryList(int CategoryId) {
            var subCategory = _dbContext.Subcategories.Where(z => z.CategoryId == CategoryId).ToList();
            var temp = Json(new SelectList(subCategory, "SubCategoryId", "SubCategoryName"));

            return Json(new SelectList(subCategory,"SubCategoryId", "SubCategoryName"));
        }


        private bool setDummyProductToPrduct(DummyProduct dp)
        {
            if (ModelState.IsValid)
            {

            
            string destinationFilePath = Path.Combine(directoryPath, dp.Image.FileName);

            Product product = new Product();
            product.ProductName = dp.ProductName;
            product.ShortDescription = dp.ShortDescription;
            product.CategoryName =_dbContext.Categories.Find(dp.CategoryName).CategoryName;
            product.SubCategoryName = dp.SubCategoryName;
            using (FileStream fileStream = new FileStream(destinationFilePath, FileMode.Create))
            {
                dp.Image.CopyTo(fileStream);
            }
            product.ImagePath = destinationFilePath;

                savePdf(dp.pdf, dp.ProductName);
                saveDescription(dp.Description, dp.ProductName);

 /*               Pdf pdf =  new Pdf(); 
            foreach (var i in dp.pdf)
            {
                destinationFilePath = Path.Combine(directoryPath , i.Files.FileName);
                using (FileStream fileStream = new FileStream(destinationFilePath, FileMode.Create))
                {
                    i.Files.CopyTo(fileStream);
                }
                Pdf pd = new Pdf { heading= i.Heading, pdfPath=destinationFilePath };
                
                product.pdfDb.Add(pd);
            }

*/

 /*           product.Description = new List<UserDescription>();
            foreach(var i in dp.Description)
            {
                UserDescription ud = new UserDescription { Title = i.Title, Heading = i.Heading, description = i.description };
                product.Description.Add(ud);
            }

*/
            product.CkEditorDescription = dp.CkEditorContent;

            product.isActive = dp.isActive;




            SaveProductDataIntoDb(product);

                return true;
            }
            return false;
        }

        private void SaveProductDataIntoDb(Product product)
        {
            _dbContext.Product.Add(product);
            _dbContext.SaveChanges();
        }
        

        private void savePdf(List<ForPdf> pdf, string productName)
        {
            foreach (var i in pdf) {
                string destinationFilePath = Path.Combine(directoryPath, i.Files.FileName);
                using (FileStream fileStream = new FileStream(destinationFilePath, FileMode.Create))
                {
                    i.Files.CopyTo(fileStream);
                }
                Pdf pd = new Pdf { pdfId= productName, heading = i.Heading, pdfPath = destinationFilePath };
                _dbContext.Pdfs.Add(pd);
                _dbContext.SaveChanges();
                _dbContext.Entry(pd).State = EntityState.Detached;

            }
            
        }

        private void saveDescription(List<UserDescription> description, string productName) {
            foreach(var i in description)
            {
                ProductDescription ud = new ProductDescription { Id = productName, Title = i.Title, Heading = i.Heading, description = i.description };
                _dbContext.UserDescription.Add(ud);
                _dbContext.SaveChanges();
                _dbContext.Entry(ud).State = EntityState.Detached;

            }
           
        }



        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();
            var categoryFromDb = _dbContext.Product.Find(id);
            if (categoryFromDb == null)
                return NotFound();
            ViewBag.FromEditAction = true;
            return RedirectToAction("Index", categoryFromDb);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (obj.CategoryName != null)
            {
         //       _db.Categories.Update(obj);
         //       _db.SaveChanges();
                return RedirectToAction("Create");
            }
            return RedirectToAction("Create");
        }






    }
}

AksApp/Controllers/SubCategoryController.cs
using AksApp.Data;
using AksApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using Microsoft.IdentityModel.Tokens;

namespace AksApp.Controllers
{
    [Authorize]
    public class SubCategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SubCategoryController(ApplicationDbContext context)
        {
            _context = context;
        }


       
        public ActionResult Create()
        {
            // This code for give the option to user to select Category
            /*     var categories = _context.Categories.Select(c => new SelectListItem
                 {
                     Value = c.CategoryId.ToString(),
                     Text = c.CategoryName
                 });

                 ViewBag.Categories = categories;
                 IEnumerable<SubCategory> objCategoriesList = _context.Subcategories.ToList();

                 ViewData["ModelList"] = objCategoriesList;

                 // Now on this code for print or show the Details of Subcategory 

                 IEnumerable<SubCategory> subCategories = _context.Subcategories.ToList();

                 ViewData["ModelList"] = subCategories;


                 */

            List<SubCategory> subCategoryList = _context.Subcategories.ToList();
            ViewBag.subCategoryList = subCategoryList;
            ViewBag.CategoryList = new SelectList(GetCategoriesList(), "CategoryId", "CategoryName");
            return View();
        }

        public List<Category> GetCategoriesList()
        {
            List<Category> categories = _context.Categories.ToList();
            return categories;
        }

        [HttpPost]
        public ActionResult Create(string selectedCategory, SubCategory subObj)
        {



            SubCategory sbTemp = new SubCategory();
            sbTemp.SubCategoryName = subObj.SubCategoryName;
            sbTemp.CategoryId = subObj.CategoryId;
            sbTemp.Category_Name = _context.Categories.Find(subObj.CategoryId).CategoryName;
            sbTemp.IsActive = subObj.IsActive;

            if(sbTemp.SubCategoryName!=null && sbTemp.Category_Name!=null && sbTemp.CategoryId!=null)
            {
                _context.Subcategories.Add(sbTemp);
                _context.SaveChanges();
                return RedirectToAction("Create");
            }

            /*
            Category temp = new Category();
            if (string.IsNullOrEmpty(selectedCategory))
            {
                ModelState.AddModelError("", "Please select a category.");
                return RedirectToAction("Create");
            }

            int categoryId = int.Parse(selectedCategory);
            

            var category = _context.Categories.Find(categoryId);

            if (category == null)
            {
                ModelState.AddModelError("", "Invalid category selected.");
                return View();
            }

            
            temp.CategoryName = category.CategoryName;
            temp.Subcategories = new List<SubCategory>
            {
                new SubCategory { SubCategoryName = subObj.SubCategoryName, Category_Name=category.CategoryName }
            };

            _context.Categories.Update(temp);
            _context.SaveChanges();
            */
            // Do something with the selected category here

            return RedirectToAction("Create");
        }

        // here writen a code for deleting the Records
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();
            var obj = _context.Subcategories.Find(id);
            if (obj == null)
                return NotFound();
            else
            {
                _context.Subcategories.Remove(obj);
                _context.SaveChanges();
            }
            return RedirectToAction("Create");


        }


        // here i Write a code for Edit the records

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();
            var categoryFromDb = _context.Subcategories.Find(id);
            if (categoryFromDb == null)
                return NotFound();

            return View(categoryFromDb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SubCategory obj)
        {
            if (obj.SubCategoryName!=null && obj.Category_Name!=null)
            {
                _context.Subcategories.Update(obj);
                _context.SaveChanges();
                return RedirectToAction("Create");
            }
            return View(obj);

            // Do something with the selected category here

            return RedirectToAction("Create");
        }


    }
}

AksApp/Views/SubCategory/Create.cshtml
@model SubCategory


<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>AKS Machine Test</title>
    <!-- slider start -->
    <!-- slider end -->
    <link rel="stylesheet" href="../css/style.css">
    <!--[if lt IE 9]>
    <script type="text/javascript" src="html5.js"></script>
    <![endif]-->
    <!--[if lt IE 7.]>
    <script defer type="text/javascript" src="pngfix1.js"></script>
    <![endif]-->
    <!-- Menu start --------------->
    <link href="../menu/quickmenu0.css" rel="stylesheet" type="text/css" media="screen" />
    <script type="text/javascript" src="../menu/quickmenu0.js"></script>
    <!-- Menu End --------------->
    <style>
        table {
            counter-reset: rowNumber;
        }

            table tr td:first-child::before {
                content: counter(rowNumber);
                counter-increment: rowNumber;
            }
    </style>
</head>
<body>
    <header>
        <div id="wrap">
            <div class="logo"><img src="../images/logo.png" border="0"></div>
            <div class="topmenu">
                <ul>
                    <li><a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
                    <li><a a asp-controller="ChangePassword" asp-action="Index">Change Password</a>&nbsp;|</li>
                    <li><a asp-controller="Admin" asp-action="LogOut"><img src="../images/logout.png" width="16" height="16" border="0" align="absmiddle">&nbsp;&nbsp;Logout</a></li>
                </ul>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </header>
    <nav>
        <ul id="qm0" class="qmmc">
            <li><a asp-controller="Admin" asp-action="admin">Dashboard</a></li>
            <li>
                <a href="#">Product</a>
                <ul>
                    <li><a asp-controller="Category" asp-action="Create">Add Category</a></li>
                    <li><a asp-controller="SubCategory" asp-action="Create">Add  Sub Category</a></li>

                    <li><a asp-controller="Product" asp-action="Index">Add Product</a></li>
                </ul>
            </li>
            <!--  <li><a href="#">CCTV</a>
                 <ul>
                   <li><a href="product-brand.html">Add Brand</a></li>
                   <li><a href="cctv.html">Add Product</a></li>
                 </ul>
             </li> -->
        </ul>
    </nav>

    <div id="wrap">
        <div class="clear" style="height:5px;"></div>
        <form method="post"  asp-action="Create">
            <input asp-for="SubCategoryId" hidden/>
            <div id="wrap2">
                <h1>Add Sub Category</h1>
                <br>

                <div class="form-raw">
                    <div class="form-name">Select Category</div>
                    <div class="form-txtfld">
                        @if (ViewBag.CategoryList != null)
                        {
                            @Html.DropDownListFor(m=>m.CategoryId,ViewBag.CategoryList as SelectList, "--Select Category Name--", new{@class ="form-control"})
                        }

                    </div>
                </div>
                <div class="clear"></div>

                <div class="form-raw">
                    <div class="form-name">Add Sub Category</div>
                    <div class="form-txtfld">
                        <input asp-for="SubCategoryName"/>
                        
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <div class="form-raw">
                <div class="form-name">Active</div>
                <div class="form-txtfld">
                    <input asp-for="IsActive">
                </div>
                <div class="clear"></div>
            </div>

            <div class="form-raw">
                <div class="form-name">&nbsp;</div>
                <div class="form-txtfld" style="width:290px;">
                    <input type="submit" class="btn" value="Submit">
                </div>
            </div>
        </form>
    </div>
    <div class="clear">&nbsp;</div>
    </div>
    <div id="wrap3">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="admintable">
                          
            <tr>
                <th width="59" align="left" valign="middle">Sr.No.</th>
                <th width="752" align="left" valign="middle">Category Name</th>
                <th width="752" align="left" valign="middle">Sub Category Name</th>
                <th width="77" align="left" valign="middle">Status</th>
                <th width="54" align="left" valign="middle">Edit</th>
                <th width="71" align="left" valign="middle">Remove</th>
            </tr>
            @if(ViewBag!=null)
            {

                @foreach (var i in ViewBag.subCategoryList ?? new List<SubCategory>())
                {
                <tr>
                    <td align="left" valign="top"></td>
                    <td align="left" valign="top">@i.Category_Name</td>
                    <td align="left" valign="top">@i.SubCategoryName</td>
                        @if (i.IsActive == true)
                        {
                            <td align="left" valign="top"><strong style="color: green">Active</strong></td>
                        }
                        else
                        {
                            <td align="left" valign="top"><strong>Active</strong></td>
                        }
                        <td align="left" valign="top"><a asp-controller="SubCategory" asp-action="Edit" asp-route-id="@i.SubCategoryId">Edit</a></td>
                        <td align="center" valign="top"><a asp-controller="SubCategory" asp-action="Delete" asp-route-id="@i.SubCategoryId"><img src="../images/icon-bin.jpg" alt="" width="25" height="25" border="0" align="absmiddle" /></a></td>
                </tr>
                }
            }
        </table>
        <div class="clear">&nbsp;</div>
    </div>
    <div class="clear"></div>
    <footer>
        <footer class="whitefoter">
            <div class="whitefooter-cont">
                <div style="float:left;">Copyright © AKS Machine Test. All Rights Reserved.</div>
                <a href="https://www.akswebsoft.com/" target="_blank" style="float:right;">
                    <img src="../images/akslogo.png" alt="AKS Websoft Consulting Pvt. Ltd." title="AKS Websoft Consulting Pvt. Ltd.">
                </a>

                <div class="clear"></div>
            </div>
        </footer>
    </footer>
</body>
</html>

AksApp/Views/SubCategory/Edit.cshtml
@model SubCategory


<form method="post" asp-action="Edit">
    <input asp-for="SubCategoryId" hidden />
    <input asp-for="Category_Name" hidden />
    <input asp-for="CategoryId" hidden />
    <div>
        <div>
            <h2 class="text-primary">
                Edit Category
            </h2>
            <hr />
        </div>
        <div class="mb-3">
            <label >Category</label>
            <input asp-for="Category_Name" disabled class="form-control" />
            
        </div>
        <div class="mb-3">
            <label asp-for="SubCategoryName"></label>
            <input asp-for="SubCategoryName" class="form-control" />
            <span asp-validation-for="SubCategoryName" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label >Active</label>
            <input asp-for="IsActive" class="form-control" />
            
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
    </div>
</form>